#!/usr/bin/env python3
"""Read-only localhost server for the live Group Resource Radar dashboard.

Why this exists: the dashboard is a static file regenerated by the cron loop
twice an hour. Opening it via ``file://`` gives a frozen snapshot, because
browsers refuse ``fetch`` on local files. Serving the same directory over
``http://127.0.0.1`` lets the page poll ``status.json`` and re-render itself
in place whenever the monitor produces new data.

Safety properties (deliberate, do not loosen without reason):

* binds loopback only; refuses any non-loopback host
* GET and HEAD only; every other method is 405
* serves an explicit whitelist of files from ``data/group-monitor``; nothing
  else is reachable (no directory listing, no SQLite, no credentials)
* symlink-escape check on every resolved path
* ``Cache-Control: no-store`` so the browser never shows a stale copy
* logs only errors, so a tab polling for weeks does not grow the log
* if the port is already held by *this* service, exits 0 so launchd stops
  retrying; if held by something else, exits 1 with a clear message
"""

from __future__ import annotations

import argparse
import datetime as dt
import email.utils
import json
import os
import signal
import socket
import subprocess
import sys
import threading
import urllib.request
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any, Dict, Optional, Tuple


os.umask(0o077)

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
import decision_store  # noqa: E402  (needs the sys.path insert above)
import http_guards  # noqa: E402  (guard module owned by lane 05; see its docstring)

DATA_DIR = ROOT / "data" / "group-monitor"
SERVICE_NAME = "group-radar"
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8765
LOOPBACK_HOSTS = {"127.0.0.1", "localhost", "::1"}
CRON_MINUTES = (17, 47)
STALE_AFTER_SECONDS = 90 * 60
MAX_FILE_BYTES = 64 * 1024 * 1024

# "Scan now": the one write-like action, and it only launches the same bounded
# loop script cron runs (which takes its own worker lock and records itself).
LOOP_SCRIPT = ROOT / "scripts" / "group_filter_loop.py"
RUN_LOG_NAME = "cron.log"
RUN_COOLDOWN_SECONDS = 10 * 60
RUN_HEADER = "X-Radar-Action"
ARCHITECTURE_REFRESH_SECONDS = 60
_last_run_started_at = 0.0
_run_lock = __import__("threading").Lock()

ROUTES: Dict[str, Tuple[str, str]] = {
    "/": ("dashboard.html", "text/html; charset=utf-8"),
    "/dashboard.html": ("dashboard.html", "text/html; charset=utf-8"),
    "/dashboard-data.json": ("dashboard-data.json", "application/json; charset=utf-8"),
    "/status.json": ("status.json", "application/json; charset=utf-8"),
    "/verification.json": ("verification.json", "application/json; charset=utf-8"),
    "/relevant.csv": ("relevant.csv", "text/csv; charset=utf-8"),
    "/relevant-sheet.csv": ("relevant-sheet.csv", "text/csv; charset=utf-8"),
    "/all-resources.csv": ("all-resources.csv", "text/csv; charset=utf-8"),
    "/relevant.jsonl": ("relevant.jsonl", "application/x-ndjson; charset=utf-8"),
    "/latest.md": ("latest.md", "text/markdown; charset=utf-8"),
    "/negative-proposals.json": ("negative-proposals.json", "application/json; charset=utf-8"),
}

HTML_CSP = (
    "default-src 'none'; img-src https: data:; script-src 'unsafe-inline'; "
    "style-src 'unsafe-inline'; connect-src 'self'; base-uri 'none'; "
    "form-action 'none'; frame-ancestors 'none'"
)

SERVER_STARTED_AT = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def utc_now() -> dt.datetime:
    return dt.datetime.now(dt.timezone.utc)


def parse_iso(value: Any) -> Optional[dt.datetime]:
    if not value:
        return None
    text = str(value).strip()
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    try:
        parsed = dt.datetime.fromisoformat(text)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=dt.timezone.utc)
    return parsed


def next_cron_run(now: Optional[dt.datetime] = None) -> dt.datetime:
    """Next :17 / :47 boundary in the machine's local time zone."""
    now = now or dt.datetime.now().astimezone()
    candidates = []
    for offset_hours in (0, 1):
        base = (now + dt.timedelta(hours=offset_hours)).replace(second=0, microsecond=0)
        for minute in CRON_MINUTES:
            candidate = base.replace(minute=minute)
            if candidate > now:
                candidates.append(candidate)
    return min(candidates)


def build_health(data_dir: Path) -> Dict[str, Any]:
    status: Dict[str, Any] = {}
    status_error = ""
    try:
        with (data_dir / "status.json").open(encoding="utf-8") as handle:
            status = json.load(handle)
    except FileNotFoundError:
        status_error = "status.json is missing"
    except (OSError, json.JSONDecodeError) as exc:
        status_error = "status.json unreadable: {}".format(exc)

    now = utc_now()
    updated = parse_iso(status.get("updated_at"))
    age_seconds = None if updated is None else max(0, int((now - updated).total_seconds()))
    stale = age_seconds is None or age_seconds > STALE_AFTER_SECONDS

    dashboard = data_dir / "dashboard.html"
    dashboard_data = data_dir / "dashboard-data.json"

    def mtime_iso(path: Path) -> Optional[str]:
        try:
            return dt.datetime.fromtimestamp(path.stat().st_mtime, tz=dt.timezone.utc).isoformat(
                timespec="seconds"
            )
        except OSError:
            return None

    next_run = next_cron_run()
    payload = {
        "service": SERVICE_NAME,
        "ok": not status_error and dashboard.exists(),
        "now": now.isoformat(timespec="seconds"),
        "server_started_at": SERVER_STARTED_AT,
        "pid": os.getpid(),
        "status_updated_at": status.get("updated_at"),
        "status_error": status_error,
        "age_seconds": age_seconds,
        "stale": stale,
        "stale_after_seconds": STALE_AFTER_SECONDS,
        "gate_ready": bool(status.get("gate_ready")),
        "resources": status.get("resources"),
        "status_counts": status.get("status_counts"),
        "dashboard_modified_at": mtime_iso(dashboard),
        "dashboard_data_modified_at": mtime_iso(dashboard_data),
        "next_run_at": next_run.isoformat(timespec="seconds"),
        "cron_minutes": list(CRON_MINUTES),
    }
    # C4 additive block (A03): per-stage truth, run summary and backoff state.
    # Liveness (`ok` above) stays what it always was — this server reachable
    # and serving fresh files — while `stages` says whether the pipeline
    # actually succeeded. A composition failure must never take down the
    # health endpoint, and must be visible rather than silently absent.
    try:
        import run_health

        payload.update(run_health.compose_health_extension(data_dir, now))
    except Exception as exc:  # noqa: BLE001
        payload.update({
            "stages": {},
            "last_run_outcome": None,
            "last_run_at": None,
            "last_semantic_success_at": None,
            "auth_required": False,
            "backlog_age_seconds": None,
            "backoff": {"active": False, "until": None, "reason": None},
            "health_extension_error": str(exc)[:200],
        })
    return payload


class RadarHandler(BaseHTTPRequestHandler):
    server_version = "GroupRadar/1.0"
    sys_version = ""
    protocol_version = "HTTP/1.1"
    data_dir: Path = DATA_DIR
    # Connection-level socket timeout: bounds how long a stalled client can
    # retain a worker thread while reading the request line/headers. Large
    # enough that a polling dashboard tab reuses its keep-alive connection
    # without idle-timeout log noise. Body reads have their own tighter
    # deadline inside http_guards.read_json_object.
    timeout = 300

    # ----- helpers -----------------------------------------------------
    def _common_headers(self, content_type: str, length: int) -> None:
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(length))
        self.send_header("Cache-Control", "no-store, max-age=0")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("Referrer-Policy", "no-referrer")
        self.send_header("X-Frame-Options", "DENY")

    def _send_json(self, code: int, payload: Dict[str, Any]) -> None:
        body = json.dumps(payload, ensure_ascii=False, indent=2).encode("utf-8")
        self.send_response(code)
        self._common_headers("application/json; charset=utf-8", len(body))
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def _send_rejection(self, rejection: "http_guards.Rejection") -> None:
        """Answer a guard rejection and, when asked, close the connection so a
        wholly or partially unread body can never be parsed as a next request."""
        status, payload, close = rejection
        body = json.dumps(payload, ensure_ascii=False, indent=2).encode("utf-8")
        self.send_response(status)
        self._common_headers("application/json; charset=utf-8", len(body))
        if close:
            self.send_header("Connection", "close")
            self.close_connection = True
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def _server_port(self) -> int:
        try:
            return int(self.server.server_address[1])
        except (AttributeError, IndexError, TypeError, ValueError):
            return -1

    def _guard_host(self) -> bool:
        """DNS-rebinding guard, every verb: Host must be this loopback server."""
        rejection = http_guards.check_host(self.headers.get("Host"), self._server_port())
        if rejection:
            self._send_rejection(rejection)
            return False
        return True

    def _resolve(self, name: str) -> Optional[Path]:
        base = self.data_dir.resolve()
        candidate = (base / name).resolve()
        if candidate.parent != base or candidate.name != name:
            return None
        return candidate

    def _serve_file(self, name: str, content_type: str) -> None:
        path = self._resolve(name)
        if path is None or not path.is_file():
            self._send_json(HTTPStatus.NOT_FOUND, {"error": "not found", "path": self.path})
            return
        try:
            stat = path.stat()
            if stat.st_size > MAX_FILE_BYTES:
                self._send_json(HTTPStatus.INSUFFICIENT_STORAGE, {"error": "artifact too large"})
                return
            etag = '"{:x}-{:x}"'.format(stat.st_mtime_ns, stat.st_size)
            if self.headers.get("If-None-Match") == etag:
                self.send_response(HTTPStatus.NOT_MODIFIED)
                self.send_header("ETag", etag)
                self.send_header("Cache-Control", "no-store, max-age=0")
                self.end_headers()
                return
            body = path.read_bytes()
        except OSError as exc:
            self._send_json(HTTPStatus.SERVICE_UNAVAILABLE, {"error": "read failed: {}".format(exc)})
            return
        self.send_response(HTTPStatus.OK)
        self._common_headers(content_type, len(body))
        self.send_header("ETag", etag)
        self.send_header("Last-Modified", email.utils.formatdate(stat.st_mtime, usegmt=True))
        if content_type.startswith("text/html"):
            self.send_header("Content-Security-Policy", HTML_CSP)
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    # ----- verbs ---------------------------------------------------------
    def do_GET(self) -> None:  # noqa: N802 (http.server naming)
        if not self._guard_host():
            return
        route = self.path.split("?", 1)[0].split("#", 1)[0]
        if route == "/api/health":
            self._send_json(HTTPStatus.OK, build_health(self.data_dir))
            return
        if route == "/api/decisions":
            # C2-T-A10 read-back (lane 02 provider; registration is 07-owned).
            code, payload = read_decisions()
            self._send_json(code, payload)
            return
        if route in {"/api/run", "/api/verdict", "/api/outcome", "/api/negative-term"}:
            # POST-only endpoints: 405 is the honest answer, not 404.
            self._reject()
            return
        if route == "/favicon.ico":
            self.send_response(HTTPStatus.NO_CONTENT)
            self.send_header("Cache-Control", "no-store")
            self.send_header("Content-Length", "0")
            self.end_headers()
            return
        target = ROUTES.get(route)
        if not target:
            self._send_json(HTTPStatus.NOT_FOUND, {"error": "not found", "path": route})
            return
        self._serve_file(*target)

    def do_HEAD(self) -> None:  # noqa: N802
        self.do_GET()

    def _reject(self) -> None:
        self.send_response(HTTPStatus.METHOD_NOT_ALLOWED)
        self.send_header("Allow", "GET, HEAD")
        self.send_header("Content-Length", "0")
        self.end_headers()

    def do_POST(self) -> None:  # noqa: N802
        if not self._guard_host():
            return
        route = self.path.split("?", 1)[0]
        if route in {"/api/verdict", "/api/outcome", "/api/negative-term"}:
            wanted = {"/api/verdict": "verdict", "/api/outcome": "outcome", "/api/negative-term": "negative-term"}[route]
            if self.headers.get(RUN_HEADER, "").strip().lower() != wanted:
                # Same 400 as always, but close: the body is unread.
                self._send_rejection(http_guards.Rejection(
                    HTTPStatus.BAD_REQUEST, {"error": "missing {} header".format(RUN_HEADER)}))
                return
            # Origin/Referer policy, content type, bounded read, JSON-object
            # shape and field hygiene — all before the handler can touch
            # stored state. See http_guards docstring for the documented
            # missing-Origin rule.
            body, rejection = http_guards.guard_mutation(self, self._server_port())
            if rejection:
                self._send_rejection(rejection)
                return
            handler = {
                "/api/verdict": record_verdict,
                "/api/outcome": record_outcome,
                "/api/negative-term": record_negative_term,
            }[route]
            code, payload = handler(body)
            self._send_json(code, payload)
            return
        if route != "/api/run":
            self._reject()
            return
        # A custom header forces a CORS preflight for any cross-origin page, and
        # the server never answers preflights, so only same-origin scripts get here.
        if self.headers.get(RUN_HEADER, "").strip().lower() != "run":
            self._send_json(HTTPStatus.BAD_REQUEST, {"error": "missing {} header".format(RUN_HEADER)})
            return
        # No body on this route, but the browser-mutation Origin policy applies.
        rejection = http_guards.check_origin(
            self.headers.get("Origin"), self.headers.get("Referer"),
            self.headers.get("Sec-Fetch-Site"), self._server_port())
        if rejection:
            self._send_rejection(rejection)
            return
        code, payload = trigger_run(self.data_dir)
        self._send_json(code, payload)

    do_PUT = do_DELETE = do_PATCH = do_OPTIONS = _reject

    # ----- logging -------------------------------------------------------
    def log_request(self, code: Any = "-", size: Any = "-") -> None:
        try:
            numeric = int(code)
        except (TypeError, ValueError):
            numeric = 0
        if numeric >= 400:
            super().log_request(code, size)

    def log_message(self, format: str, *args: Any) -> None:  # noqa: A002
        sys.stderr.write(
            "[radar-server {}] {}\n".format(
                dt.datetime.now().isoformat(timespec="seconds"), format % args
            )
        )
        sys.stderr.flush()


VERDICTS_PATH = ROOT / "config" / "verdicts.json"
OUTCOMES_PATH = ROOT / "config" / "outcomes.json"
PROFILE_PATH = ROOT / "config" / "group-filter-profile.json"
# The scanner's own tool projection: the trusted server-side answer to "what
# kind of thing is this key", so type rules never depend only on client input.
TOOL_INDEX_PATH = DATA_DIR / "dashboard-data.json"
_profile_lock = __import__("threading").Lock()
ALLOWED_VERDICTS = {"must_try", "must_read", "excluded", "already_have"}
# What happened after a recommendation, as opposed to whether to make one.
ALLOWED_OUTCOMES = {"trying", "kept", "dropped"}
_verdict_lock = __import__("threading").Lock()
_outcome_lock = __import__("threading").Lock()


def lookup_tool_type(key: str) -> str:
    """Canonical resource type for a tool key, from the scanner's projection.

    Returns "" when the index is missing, unreadable, or has no opinion; the
    caller then falls back to what the client offered. Never raises: typing is
    an enrichment here, and a broken index must not block a decision save.
    """
    import resource_typing

    try:
        raw = TOOL_INDEX_PATH.read_bytes()
    except OSError:
        return ""
    if len(raw) > MAX_FILE_BYTES:
        return ""
    try:
        payload = json.loads(raw.decode("utf-8"))
    except (ValueError, UnicodeDecodeError):
        return ""
    tools = payload.get("tools") if isinstance(payload, dict) else None
    if not isinstance(tools, list):
        return ""
    wanted = key.lower()
    for tool in tools:
        if isinstance(tool, dict) and str(tool.get("key", "")).lower() == wanted:
            candidate = str(tool.get("resource_type") or "")
            return candidate if candidate in resource_typing.RESOURCE_TYPES else ""
    return ""


def _parse_expected_revision(body: Dict[str, Any]) -> Tuple[Optional[int], Optional[Dict[str, Any]]]:
    """Optional optimistic-concurrency input; garbage gets a clear 400."""
    value = body.get("expected_revision")
    if value is None:
        return None, None
    if isinstance(value, bool) or not isinstance(value, int) or value < 0:
        return None, {"error": "expected_revision must be a non-negative integer"}
    return value, None


# What a measured trial may additionally record (all optional; an unmeasured
# number stays absent — unknown is never fabricated into a result). Strings
# are length-capped; baseline/observed_result may be real numbers.
OUTCOME_TRIAL_FIELDS: Dict[str, int] = {
    "project": 120,
    "artifact": 200,
    "success_measure": 300,
    "baseline": 120,
    "observed_result": 300,
    "units": 40,
    "evidence": 600,
}


def _collect_trial_fields(body: Dict[str, Any]) -> Tuple[Dict[str, Any], Optional[Dict[str, Any]]]:
    """Validate the optional trial fields; only provided values are stored."""
    collected: Dict[str, Any] = {}
    for field, cap in OUTCOME_TRIAL_FIELDS.items():
        value = body.get(field)
        if value in (None, ""):
            continue
        if field in ("baseline", "observed_result") and isinstance(value, (int, float)) \
                and not isinstance(value, bool):
            collected[field] = value
            continue
        if not isinstance(value, str):
            return {}, {"error": "{} must be a string{}".format(
                field, " or a number" if field in ("baseline", "observed_result") else "")}
        collected[field] = value[:cap]
    trial_date = body.get("trial_date")
    if trial_date not in (None, ""):
        try:
            collected["trial_date"] = dt.date.fromisoformat(str(trial_date)).isoformat()
        except ValueError:
            return {}, {"error": "trial_date must be a YYYY-MM-DD date"}
    return collected, None


def record_verdict(body: Dict[str, Any], *, source: str = "dashboard",
                   source_event: str = "", actor: str = "") -> Tuple[int, Dict[str, Any]]:
    """Append or replace one hand-made verdict in config/verdicts.json.

    The whole point of the review queue is that the judgement stays the user's,
    so this is the shared validated write path for every ingress (dashboard
    HTTP, Telegram pull, agent sessions) and it writes exactly one reviewed
    entry per call. Persistence goes through ``decision_store``: inter-process
    locked, corruption fails closed with the bytes untouched, publication is
    atomic and durable, prior versions stay recoverable, and the response
    carries the authoritative stored record plus its on-disk revision.

    ``source``/``source_event``/``actor`` are server-side provenance chosen by
    the calling ingress, never by the request body: a browser cannot claim to
    be Telegram.
    """
    key = str(body.get("key") or "").strip().lstrip("/")
    verdict = str(body.get("verdict") or "").strip()
    if not key or "/" not in key:
        return HTTPStatus.BAD_REQUEST, {"error": "key must look like host/owner/name"}
    if verdict not in ALLOWED_VERDICTS and verdict != "clear":
        return HTTPStatus.BAD_REQUEST, {
            "error": "verdict must be one of {} or 'clear'".format(sorted(ALLOWED_VERDICTS))
        }
    expected_revision, revision_error = _parse_expected_revision(body)
    if revision_error:
        return HTTPStatus.BAD_REQUEST, revision_error

    # A verdict must fit what the thing actually is. "Must try" on an article
    # and "must read" on a CLI are category errors, and storing one silently
    # is how the two kinds get conflated in the first place. The type comes
    # from the client when offered, otherwise from the server's own tool
    # index, so the Telegram path is held to exactly the same rule as HTTP.
    import resource_typing

    resource_type = str(body.get("resource_type") or "").strip()
    type_source = "client" if resource_type else ""
    if resource_type and resource_type not in resource_typing.RESOURCE_TYPES:
        return HTTPStatus.BAD_REQUEST, {
            "error": "unknown resource_type '{}'; expected one of {}".format(
                resource_type, sorted(resource_typing.RESOURCE_TYPES)
            )
        }
    if not resource_type:
        resource_type = lookup_tool_type(key)
        type_source = "server_index" if resource_type else ""
    if verdict != "clear" and resource_type:
        if not resource_typing.verdict_fits_type(verdict, resource_type):
            allowed = sorted(resource_typing.VERDICT_FOR_TYPE.get(resource_type, set()))
            return HTTPStatus.CONFLICT, {
                "error": "'{}' does not fit a '{}' resource; allowed here: {}".format(
                    verdict, resource_type, allowed
                ),
                "hint": "{} means: {}".format(
                    resource_type, resource_typing.TYPE_VERBS.get(resource_type, "")
                ),
            }

    with _verdict_lock:
        try:
            with decision_store.locked_document(VERDICTS_PATH, "verdicts") as store:
                if expected_revision is not None and expected_revision != store.revision:
                    return HTTPStatus.CONFLICT, {
                        "error": "verdicts.json changed since this view was loaded",
                        "current_revision": store.revision,
                    }
                document = store.document
                entries = document["verdicts"]
                remaining = [e for e in entries if str(e.get("key", "")).lower() != key.lower()]
                removed = len(entries) - len(remaining)
                entry: Optional[Dict[str, Any]] = None
                if verdict == "clear":
                    document["verdicts"] = remaining
                    action = "cleared" if removed else "not present"
                else:
                    entry = {
                        "key": key,
                        "name": str(body.get("name") or key)[:200],
                        "verdict": verdict,
                        "why": str(body.get("why") or "")[:600],
                        "what": str(body.get("what") or "")[:400],
                        "first_step": str(body.get("first_step") or "")[:400],
                        "lane": str(body.get("lane") or "")[:120],
                        "reason_code": str(body.get("reason_code") or "")[:40],
                        "resource_type": resource_type,
                        "decided_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
                        "decided_by": source,
                    }
                    if type_source:
                        entry["resource_type_source"] = type_source
                    if source_event:
                        entry["source_event"] = str(source_event)[:80]
                    if actor:
                        entry["actor"] = str(actor)[:120]
                    for field in ("stars", "license", "last_push"):
                        if body.get(field) not in (None, ""):
                            entry[field] = body[field]
                    if verdict == "must_try":
                        ranks = [
                            int(e["rank"])
                            for e in remaining
                            if e.get("verdict") == "must_try" and isinstance(e.get("rank"), int)
                        ]
                        entry["rank"] = (max(ranks) + 1) if ranks else 1
                    remaining.append(entry)
                    document["verdicts"] = remaining
                    action = "replaced" if removed else "added"
                document["updated_at"] = dt.datetime.now(dt.timezone.utc).date().isoformat()
                revision = store.commit()
        except decision_store.StoreError as exc:
            return exc.status, exc.payload
    return HTTPStatus.OK, {
        "ok": True,
        "action": action,
        "key": key,
        "verdict": verdict,
        "total": len(document["verdicts"]),
        "revision": revision,
        "record": entry,
        "note": "Takes effect in the dashboard after the next export (within 30 minutes) or Scan now.",
    }


def record_outcome(body: Dict[str, Any], *, source: str = "dashboard") -> Tuple[int, Dict[str, Any]]:
    """Append or replace one outcome in config/outcomes.json.

    Structurally identical to record_verdict, deliberately: one validated,
    inter-process-locked, atomic write path per file, so neither can drift
    from the other. Kept in a separate file because clearing a verdict must
    not erase the fact that you tried the thing. ``source`` is server-side
    provenance chosen by the ingress, never taken from the body.
    """
    key = str(body.get("key") or "").strip().lstrip("/")
    state = str(body.get("state") or "").strip()
    if not key or "/" not in key:
        return HTTPStatus.BAD_REQUEST, {"error": "key must look like host/owner/name"}
    if state not in ALLOWED_OUTCOMES and state != "clear":
        return HTTPStatus.BAD_REQUEST, {
            "error": "state must be one of {} or 'clear'".format(sorted(ALLOWED_OUTCOMES))
        }
    expected_revision, revision_error = _parse_expected_revision(body)
    if revision_error:
        return HTTPStatus.BAD_REQUEST, revision_error
    trial_fields, trial_error = _collect_trial_fields(body)
    if trial_error:
        return HTTPStatus.BAD_REQUEST, trial_error
    with _outcome_lock:
        try:
            with decision_store.locked_document(OUTCOMES_PATH, "outcomes") as store:
                if expected_revision is not None and expected_revision != store.revision:
                    return HTTPStatus.CONFLICT, {
                        "error": "outcomes.json changed since this view was loaded",
                        "current_revision": store.revision,
                    }
                document = store.document
                entries = document["outcomes"]
                remaining = [e for e in entries if str(e.get("key", "")).lower() != key.lower()]
                removed = len(entries) - len(remaining)
                entry: Optional[Dict[str, Any]] = None
                if state == "clear":
                    document["outcomes"] = remaining
                    action = "cleared" if removed else "not present"
                else:
                    entry = {
                        "key": key,
                        "name": str(body.get("name") or key)[:200],
                        "state": state,
                        "note": str(body.get("note") or "")[:600],
                        "decided_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
                        "decided_by": source,
                    }
                    entry.update(trial_fields)
                    remaining.append(entry)
                    document["outcomes"] = remaining
                    action = "replaced" if removed else "added"
                document["updated_at"] = dt.datetime.now(dt.timezone.utc).date().isoformat()
                revision = store.commit()
        except decision_store.StoreError as exc:
            return exc.status, exc.payload
    return HTTPStatus.OK, {
        "ok": True,
        "action": action,
        "key": key,
        "state": state,
        "total": len(document["outcomes"]),
        "revision": revision,
        "record": entry,
    }


def record_negative_term(body: Dict[str, Any]) -> Tuple[int, Dict[str, Any]]:
    """Approve or withdraw one learned exclusion term.

    Writes to selection.negative_terms in the filter profile. Approving a rule is
    a bigger act than judging one tool, so the term is validated hard: it must be
    a single short token, and it may never shadow a term the profile already
    relies on to *accept* things.
    """
    term = str(body.get("term") or "").strip().lower()
    action = str(body.get("action") or "add").strip()
    if not term or len(term) < 3 or len(term) > 40 or any(c.isspace() for c in term):
        return HTTPStatus.BAD_REQUEST, {"error": "term must be a single token of 3-40 characters"}
    if action not in {"add", "remove"}:
        return HTTPStatus.BAD_REQUEST, {"error": "action must be 'add' or 'remove'"}
    with _profile_lock:
        try:
            with decision_store.locked_document(
                PROFILE_PATH, None, require_existing=True, bump_revision=False
            ) as store:
                profile = store.document
                selection = profile.get("selection")
                if not isinstance(selection, dict):
                    return HTTPStatus.INTERNAL_SERVER_ERROR, {"error": "profile has no selection block"}

                positive = {str(t).lower() for t in selection.get("ai_terms", [])}
                for area in (selection.get("project_areas") or {}).values():
                    positive.update(str(t).lower() for t in area.get("keywords", []))
                if action == "add" and term in positive:
                    return HTTPStatus.CONFLICT, {
                        "error": "'{}' is already a positive term; excluding on it would fight the rule beside it".format(term)
                    }

                current = [str(t) for t in selection.get("negative_terms", [])]
                if action == "add":
                    if term in (t.lower() for t in current):
                        return HTTPStatus.OK, {"ok": True, "action": "already present", "term": term, "total": len(current)}
                    current.append(term)
                else:
                    current = [t for t in current if t.lower() != term]
                selection["negative_terms"] = current
                store.commit()
        except decision_store.StoreError as exc:
            # Keep the long-standing external answer for a broken profile.
            if exc.status != HTTPStatus.SERVICE_UNAVAILABLE:
                return HTTPStatus.INTERNAL_SERVER_ERROR, {"error": "profile is unreadable"}
            return exc.status, exc.payload
    return HTTPStatus.OK, {
        "ok": True,
        "action": "added" if action == "add" else "removed",
        "term": term,
        "total": len(current),
        "note": "Applies to items the positive rules did not match, from the next scan on.",
    }


def read_decisions() -> Tuple[int, Dict[str, Any]]:
    """Fresh authoritative read-back of both authored decision files.

    Implementation for the C2-T-A10 additive route ``GET /api/decisions``
    (route registration itself belongs to the coordinator's dispatch). A
    successful save followed by this read must show the saved record without
    waiting for the next scanner export; a missing file is honestly an empty
    document, while a corrupt file is reported as an error instead of being
    passed off as empty history.
    """
    payload: Dict[str, Any] = {
        "ok": True,
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
        "verdicts_document": None,
        "outcomes_document": None,
        "revision": {"verdicts": None, "outcomes": None},
    }
    for name, path, container in (
        ("verdicts", VERDICTS_PATH, "verdicts"),
        ("outcomes", OUTCOMES_PATH, "outcomes"),
    ):
        document, revision, error = decision_store.read_document(path, container)
        if error:
            payload["ok"] = False
            payload.setdefault("errors", {})[name] = error
        else:
            payload["{}_document".format(name)] = document
            payload["revision"][name] = revision
    return HTTPStatus.OK, payload


def worker_lock_is_free(data_dir: Path) -> bool:
    """True when no monitor run currently holds data/group-monitor/worker.lock."""
    import fcntl

    lock_path = data_dir / "worker.lock"
    try:
        handle = lock_path.open("a+")
    except OSError:
        return True
    try:
        fcntl.flock(handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError:
        return False
    else:
        fcntl.flock(handle.fileno(), fcntl.LOCK_UN)
        return True
    finally:
        handle.close()


def trigger_run(data_dir: Path, now: Optional[float] = None) -> Tuple[int, Dict[str, Any]]:
    """Start one bounded monitor run in the background (the same script cron runs)."""
    global _last_run_started_at
    import time

    now = time.monotonic() if now is None else now
    with _run_lock:
        elapsed = now - _last_run_started_at
        if _last_run_started_at and elapsed < RUN_COOLDOWN_SECONDS:
            return HTTPStatus.TOO_MANY_REQUESTS, {
                "started": False,
                "reason": "a scan was started {} s ago; wait {} s".format(
                    int(elapsed), int(RUN_COOLDOWN_SECONDS - elapsed)
                ),
            }
        if not LOOP_SCRIPT.exists():
            return HTTPStatus.SERVICE_UNAVAILABLE, {"started": False, "reason": "loop script is missing"}
        if not worker_lock_is_free(data_dir):
            return HTTPStatus.CONFLICT, {"started": False, "reason": "a scan is already running"}
        runtime_path = os.pathsep.join(
            path
            for path in ("/opt/homebrew/bin", "/usr/local/bin", "/usr/bin", "/bin", "/usr/sbin", "/sbin")
        )
        try:
            log_handle = (data_dir / RUN_LOG_NAME).open("a")
            process = subprocess.Popen(
                [sys.executable, str(LOOP_SCRIPT)],
                cwd=str(LOOP_SCRIPT.parent.parent),
                stdout=log_handle,
                stderr=subprocess.STDOUT,
                env={**os.environ, "PATH": runtime_path},
                start_new_session=True,
            )
            log_handle.close()
        except OSError as exc:
            return HTTPStatus.SERVICE_UNAVAILABLE, {"started": False, "reason": "could not start: {}".format(exc)}
        _last_run_started_at = now
        return HTTPStatus.ACCEPTED, {"started": True, "pid": process.pid, "cooldown_seconds": RUN_COOLDOWN_SECONDS}


def probe_existing(host: str, port: int) -> Optional[Dict[str, Any]]:
    try:
        with urllib.request.urlopen(
            "http://{}:{}/api/health".format(host, port), timeout=2
        ) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except Exception:
        return None
    return payload if isinstance(payload, dict) else None


def architecture_refresh_loop(stop: threading.Event) -> None:
    """Keep documentation fresh without blocking requests or retaining old imports."""
    while not stop.is_set():
        try:
            result = subprocess.run(
                [sys.executable, str(ROOT / "scripts" / "generate_architecture.py"), "--refresh"],
                cwd=str(ROOT), capture_output=True, text=True, timeout=30, check=False,
            )
            if result.returncode:
                print("architecture refresh failed: " + (result.stderr or result.stdout)[-400:], file=sys.stderr, flush=True)
        except (OSError, subprocess.TimeoutExpired) as exc:
            print("architecture refresh failed: " + str(exc), file=sys.stderr, flush=True)
        if stop.wait(ARCHITECTURE_REFRESH_SECONDS):
            break


def serve(host: str, port: int, data_dir: Path) -> int:
    if host not in LOOPBACK_HOSTS:
        print("radar-server: refusing to bind non-loopback host {}".format(host), file=sys.stderr)
        return 2
    RadarHandler.data_dir = data_dir
    ThreadingHTTPServer.allow_reuse_address = True
    ThreadingHTTPServer.daemon_threads = True
    try:
        server = ThreadingHTTPServer((host, port), RadarHandler)
    except OSError as exc:
        existing = probe_existing(host, port)
        if existing and existing.get("service") == SERVICE_NAME:
            print(
                "radar-server: port {} already served by {} pid {}; nothing to do".format(
                    port, SERVICE_NAME, existing.get("pid")
                ),
                file=sys.stderr,
            )
            return 0
        print("radar-server: cannot bind {}:{} ({})".format(host, port, exc), file=sys.stderr)
        return 1

    def _stop(signum: int, _frame: Any) -> None:
        raise SystemExit(0)

    signal.signal(signal.SIGTERM, _stop)
    signal.signal(signal.SIGINT, _stop)
    print(
        "radar-server: serving {} at http://{}:{}/ (pid {})".format(data_dir, host, port, os.getpid()),
        file=sys.stderr,
    )
    sys.stderr.flush()
    architecture_stop = threading.Event()
    architecture_worker = threading.Thread(
        target=architecture_refresh_loop, args=(architecture_stop,), daemon=True,
        name="architecture-refresh",
    )
    architecture_worker.start()
    try:
        server.serve_forever(poll_interval=0.5)
    except SystemExit:
        pass
    finally:
        architecture_stop.set()
        architecture_worker.join(timeout=31)
        server.server_close()
    return 0


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default=DEFAULT_HOST, help="loopback host only")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--data-dir", type=Path, default=DATA_DIR)
    parser.add_argument(
        "--health",
        action="store_true",
        help="print the health document for the given host/port and exit",
    )
    args = parser.parse_args(argv)
    if args.health:
        payload = probe_existing(args.host, args.port)
        if not payload:
            print(json.dumps({"ok": False, "error": "no radar server responding"}))
            return 1
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return 0 if payload.get("ok") else 1
    return serve(args.host, args.port, args.data_dir)


if __name__ == "__main__":
    sys.exit(main())
